# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'your-container-image-name:$(build.buildId)'

steps:
- task: Docker@0
  displayName: 'Build an image'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryConnection: 'vcp-sh-docker-hub-ssoserver'
    imageName: vcpsh/ssoserver

- task: Docker@0
  displayName: 'Push an image'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryConnection: 'vcp-sh-docker-hub-ssoserver'
    action: 'Push an image'
    imageName: vcpsh/ssoserver
    includeLatestTag: true

resources:
- repo: self